[2025-06-08T22:20:06.130+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T22:20:06.142+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: backfill_pollution_weather_dag.fetch_full_history_all_cities manual__2025-06-08T20:19:56.840279+00:00 [queued]>
[2025-06-08T22:20:06.145+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: backfill_pollution_weather_dag.fetch_full_history_all_cities manual__2025-06-08T20:19:56.840279+00:00 [queued]>
[2025-06-08T22:20:06.145+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-06-08T22:20:06.161+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_full_history_all_cities> on 2025-06-08 20:19:56.840279+00:00
[2025-06-08T22:20:06.164+0200] {standard_task_runner.py:63} INFO - Started process 1133012 to run task
[2025-06-08T22:20:06.167+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'backfill_pollution_weather_dag', 'fetch_full_history_all_cities', 'manual__2025-06-08T20:19:56.840279+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/backfill_dag.py', '--cfg-path', '/tmp/tmpkz6aumiz']
[2025-06-08T22:20:06.168+0200] {standard_task_runner.py:91} INFO - Job 265: Subtask fetch_full_history_all_cities
[2025-06-08T22:20:06.196+0200] {task_command.py:426} INFO - Running <TaskInstance: backfill_pollution_weather_dag.fetch_full_history_all_cities manual__2025-06-08T20:19:56.840279+00:00 [running]> on host DESKTOP-2QS8J6D.
[2025-06-08T22:20:06.259+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='backfill_pollution_weather_dag' AIRFLOW_CTX_TASK_ID='fetch_full_history_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T20:19:56.840279+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T20:19:56.840279+00:00'
[2025-06-08T22:20:06.260+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T22:20:26.339+0200] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-08T22:20:26.339+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-08T22:20:26.340+0200] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 1133012. PIDs of all processes in the group: [1133012]
[2025-06-08T22:20:26.340+0200] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 1133012
[2025-06-08T22:20:26.340+0200] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-08T22:20:26.341+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T22:20:26.367+0200] {process_utils.py:80} INFO - Process psutil.Process(pid=1133012, status='terminated', exitcode=0, started='22:20:06') (1133012) terminated with exit code 0
